default_platform(:ios)

platform :ios do
  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Deploying to App store"
  lane :release do
    screenshot
    increment_build_number
  end
end
