name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Bundler
        run: |
          gem install bundler:1.17.3
          bundle update --bundler

      - name: Install Cocoapods
        run: sudo gem install cocoapods
